version: '3.9'

services:
  backend:
    build: 
      context: ./server
      dockerfile: docker/Dockerfile
  
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - PORT=8080
      - MODE=debug
      - DBUSER=postgres
      - DBPASSWORD=password
      - DBHOST=database
      - DBPORT=5432
      - DB=posts
    restart: always
  
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=posts
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database-volume:/var/lib/postgresql/data
    